version: 2

models:
  - name: stg_customers
    description: "Cleaned customers data from raw source"
    columns:
      - name: customer_id
        description: "Primary key"
        data_tests:
          - unique
          - not_null

  - name: stg_orders
    description: "Cleaned orders data from raw source"
    columns:
      - name: order_id
        description: "Primary key"
        data_tests:
          - unique
          - not_null
      - name: customer_id
        data_tests:
          - not_null
      - name: status
        data_tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']

  - name: stg_payments
    description: "Cleaned payments data from raw source"
    columns:
      - name: payment_id
        description: "Primary key"
        data_tests:
          - unique
          - not_null
      - name: payment_method
        data_tests:
          - accepted_values:
              values: ['credit_card', 'coupon', 'bank_transfer', 'gift_card']

